# File: src\docker\Dockerfile_frontend

FROM python:3.10-slim

# Désactive la collecte de statistiques
ENV STREAMLIT_BROWSER_GATHER_USAGE_STATS=false

WORKDIR /app

COPY src/docker/requirements_frontend.txt .

RUN pip install --no-cache-dir -r requirements_frontend.txt

COPY src/frontend ./frontend

EXPOSE 8501

CMD ["streamlit", "run", "frontend/app.py"]