# File: src\docker\Dockerfile_airflow

FROM apache/airflow:2.8.1

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libxml2-dev \
    libxslt1-dev \
    libffi-dev \
    libssl-dev \
    python3-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONPATH="${PYTHONPATH}:/opt/airflow/etl"

USER airflow

COPY src/docker/requirements_airflow.txt .

RUN pip install --no-cache-dir -r requirements_airflow.txt

CMD ["airflow", "webserver"]